import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../css/globals.css";
import dbConn from "../mongodb/connection/dbConn.js"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/4346990.jpg", // Path to your favicon
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  dbConn()
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
