import LayoutMain from "@/components/admin/layout/layoutMain";
import { Inter } from "next/font/google";
import "../../css/adminPanal.css";
import SideBarMain from "@/components/admin/layout/sidebar/SideBarMain";
import LogoutBtn from "@/components/admin/layout/navbar/LogoutBtn";
import SearchForm from "@/components/admin/layout/navbar/SearchForm";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "my page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <LayoutMain
      children={children}
      SideBarMain={<SideBarMain />}
      LogoutBtn={<LogoutBtn text={"Logout"} />}
    />
  );
}
